name: Promote Snap

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable

env:
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

jobs:
  promote:
    name: Promote Snap
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo snap install --classic --channel edge snapcraft
      - name: Set target channel
        env:
          PROMOTE_FROM: ${{ github.event.inputs.promotion }}
        run: |
          if [ "${PROMOTE_FROM}" == "edge -> beta" ]; then
            echo "promote-from=edge" >> ${GITHUB_ENV}
            echo "promote-to=beta" >> ${GITHUB_ENV}
          elif [ "${PROMOTE_FROM}" == "beta -> candidate" ]; then
            echo "promote-from=beta" >> ${GITHUB_ENV}
            echo "promote-to=candidate" >> ${GITHUB_ENV}
          elif [ "${PROMOTE_FROM}" == "candidate -> stable" ]; then
            echo "promote-from=candidate" >> ${GITHUB_ENV}
            echo "promote-to=stable" >> ${GITHUB_ENV}
          fi
      - name: Fetch Revision
        run: |
          SNAP_RELEASES=$(curl -s -H "Snap-Device-Series: 16" "http://api.snapcraft.io/v2/snaps/info/snmp-notifier?fields=revision")
          REVISION=$(echo $SNAP_RELEASES | jq '."channel-map"[] | select(.channel.risk=="${{ env.promote-from }}").revision')
          echo "revision=$REVISION" >> ${GITHUB_ENV}
      - name: Promote Snap
        run: |
          snapcraft release snmp-notifier ${{ env.revision }} ${{ env.promote-to }}
